In [65]:
#Çalışmamızın bu kısmında farklı Classification Algoritmalarının karşılaştırılması üzerine durulacaktır.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [66]:
df=pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [67]:
#Datasetin kaç satır,sütundan oluştuğuna bakmak için gerekli
df.shape

(768, 9)

In [68]:
#Kolonların data type ları hakkında bilgi alma
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [69]:
#Dataset hakkındaki sayısal değerler.
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [70]:
#Satırlarda eksik değer olup olmadığının kontrolü
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [71]:
#Kolon isimlerini alır
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [72]:
#Sağlık verilerinin çoğunda 0 olma ihtimali yok denecek kadar azdır.Bu kolonların tespiti

columns_to_check=["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

for col in columns_to_check:
    zero_count=(df[col]==0).sum()
    zero_percentage=100*zero_count/len(df)
    print(f"{col}:{zero_count} %{zero_percentage:.2f}")

Glucose:5 %0.65
BloodPressure:35 %4.56
SkinThickness:227 %29.56
Insulin:374 %48.70
BMI:11 %1.43

In [73]:
#independent,dependent feautureların belirlenmesi
X=df.drop("Outcome",axis=1)
y=df["Outcome"]

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)

In [75]:
#Datasette tespit edilen 0 a eşit olan satırların doldurulması
#Burada median değeri sadece train verisinde hesaplandı.Test verisi doldurulurken train de elde edilen median değeriyle dolduruldu.
columns_to_fill=["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

medians={}

for col in columns_to_fill:
    median_value=X_train[X_train[col]!=0][col].median()
    medians[col]=median_value
    X_train[col]=X_train[col].replace(0,median_value)

for col in columns_to_fill:
    X_test[col]=X_test[col].replace(0,medians[col])

In [76]:
X_train.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,3.907166,121.560261,72.612378,29.040717,142.477199,32.448208,0.469948,33.285016
std,3.385438,29.974412,12.165642,8.312217,80.879330,6.862948,0.328516,11.678337
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.084000,21.000000
25%,1.000000,100.000000,64.000000,25.000000,125.000000,27.600000,0.238250,24.000000
50%,3.000000,117.000000,72.000000,29.000000,129.500000,32.300000,0.370500,29.000000
75%,6.000000,139.750000,80.000000,32.000000,130.000000,36.500000,0.630750,40.000000
max,17.000000,199.000000,122.000000,63.000000,680.000000,67.100000,2.420000,81.000000

In [77]:
X_test.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000
mean,3.597403,122.038961,71.487013,29.376623,144.402597,32.483117,0.479565,33.064935
std,3.304818,32.320876,11.813495,10.513035,104.291511,6.946159,0.343303,12.118519
min,0.000000,61.000000,30.000000,7.000000,23.000000,18.400000,0.078000,21.000000
25%,1.000000,95.250000,64.000000,23.250000,108.250000,26.925000,0.254000,24.000000
50%,3.000000,117.000000,72.000000,29.000000,129.500000,32.300000,0.376500,28.000000
75%,5.750000,142.750000,80.000000,33.750000,129.500000,36.950000,0.603750,41.000000
max,13.000000,197.000000,106.000000,99.000000,846.000000,55.000000,2.329000,69.000000

In [78]:
#Bazı algoritmalar için gereklidir
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [79]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

#Model eğitim sonrası hesaplanacak değerlerin fonksiyon aracılığıyla hazırlanması
def calculate_model_metric(true,predicted):
    cr=classification_report(true,predicted)
    cm=confusion_matrix(true,predicted)
    acc=accuracy_score(true,predicted)

    print("Classification Report:\n",cr)
    print("Confusion Matrix:\n",cm)
    print("Accuracy Score:\n",acc)
    print("-----------------------")

    return cr,cm,acc

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

In [81]:
#Model eğitimi yapılacak algoritmalar
models={
    "Logistic Regression":LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "SVC":SVC(),
    "AdaBoosting":AdaBoostClassifier()
}

In [82]:
for name, model in models.items():

    print("Model:", name)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    calculate_model_metric(y_test, y_pred)

Model: Logistic Regression
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.82      0.82       108
           1       0.59      0.59      0.59        46

    accuracy                           0.75       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.75      0.75      0.75       154

Confusion Matrix:
 [[89 19]
 [19 27]]
Accuracy Score:
 0.7532467532467533
-----------------------
Model: KNN
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.75      0.78       108
           1       0.49      0.57      0.53        46

    accuracy                           0.69       154
   macro avg       0.65      0.66      0.65       154
weighted avg       0.71      0.69      0.70       154

Confusion Matrix:
 [[81 27]
 [20 26]]
Accuracy Score:
 0.6948051948051948
-----------------------
Model: Decision Tree
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.72      0.77       108
           1       0.49      0.63      0.55        46

    accuracy                           0.69       154
   macro avg       0.66      0.68      0.66       154
weighted avg       0.72      0.69      0.70       154

Confusion Matrix:
 [[78 30]
 [17 29]]
Accuracy Score:
 0.6948051948051948
-----------------------
Model: Random Forest
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.79      0.81       108
           1       0.56      0.63      0.59        46

    accuracy                           0.74       154
   macro avg       0.70      0.71      0.70       154
weighted avg       0.75      0.74      0.74       154

Confusion Matrix:
 [[85 23]
 [17 29]]
Accuracy Score:
 0.7402597402597403
-----------------------
Model: SVC
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.81      0.81       108
           1       0.54      0.54      0.54        46

    accuracy                           0.73       154
   macro avg       0.67      0.67      0.67       154
weighted avg       0.73      0.73      0.73       154

Confusion Matrix:
 [[87 21]
 [21 25]]
Accuracy Score:
 0.7272727272727273
-----------------------
Model: AdaBoosting
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.81      0.82       108
           1       0.58      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.76       154

Confusion Matrix:
 [[87 21]
 [17 29]]
Accuracy Score:
 0.7532467532467533
-----------------------

In [ ]:
#hyperparameter tuning (Logistic Regression ve AdaBoost için)

log_params = {
    "penalty": ['l1', 'l2'],
    "C": [0.001, 0.01, 0.1, 1, 10, 100],
    "solver": ['liblinear'],
    "max_iter": [100, 200, 500]
}

ada_params= {
    "n_estimators": [50,70,100,120,150,200],
    "learning_rate":[0.001,0.01,0.1,1,10]
}

In [84]:
param_models= [
    ("Log",LogisticRegression(),log_params),
    ("AdaBoost",AdaBoostClassifier(),ada_params)
]

In [85]:
from sklearn.model_selection import GridSearchCV

for name,model,params in param_models:
    grid=GridSearchCV(estimator=model,param_grid=params,n_jobs=-1,cv=5)
    grid.fit(X_train,y_train)

    print("Best params for:",name,grid.best_params_)

Best params for: Log {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'}
Best params for: AdaBoost {'learning_rate': 1, 'n_estimators': 150}

In [86]:
log_reg=LogisticRegression(C=1,max_iter=100,penalty="l1",solver="liblinear")
log_reg.fit(X_train,y_train)

log_reg_pred=log_reg.predict(X_test)

print("Accuracy Score:",accuracy_score(y_test,log_reg_pred))

Accuracy Score: 0.7597402597402597

In [87]:
ada_boost=AdaBoostClassifier(learning_rate=1,n_estimators=150)
ada_boost.fit(X_train,y_train)

ada_pred=ada_boost.predict(X_test)

print("Accuracy Score:",accuracy_score(y_test,ada_pred))

Accuracy Score: 0.7597402597402597